# Generated by Django 3.2.5 on 2021-08-06 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': '测试人员', 'verbose_name_plural': '测试人员'},
        ),
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name': '项目', 'verbose_name_plural': '项目'},
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='project',
            new_name='project_name',
        ),
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.IntegerField(verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=200, verbose_name='测试人员名称'),
        ),
        migrations.AlterField(
            model_name='person',
            name='sex',
            field=models.CharField(max_length=200, verbose_name='性别'),
        ),
        migrations.AlterModelTable(
            name='person',
            table='tb_person',
        ),
        migrations.AlterModelTable(
            name='projects',
            table='tb_project',
        ),
    ]
