# Generated by Django 3.2.5 on 2021-08-06 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_person_project_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='project_id',
            new_name='project',
        ),
    ]
