# Generated by Django 3.2.5 on 2021-08-11 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20210806_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interfaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='接口名称')),
                ('tester', models.CharField(max_length=200, verbose_name='测试人员名称')),
                ('desc', models.CharField(max_length=200, verbose_name='接口描述')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.projects')),
            ],
            options={
                'verbose_name': '接口名称',
                'verbose_name_plural': '接口名称',
                'db_table': 'tb_interface',
            },
        ),
    ]
